# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "check")
  end

  desc "bump changelog and upload release to maven central"
    lane :createSSMCRelease do
      version_name = sh("grep VERSION_NAME ../SecretSauce/gradle.properties | awk -F '=' '{print $2}'")
      stamp_changelog(section_identifier: "Build #{version_name}")
      gradle(task: ":SecretSauce:clean :SecretSauce:build :SecretSauce:check :SecretSauce:upAr")
    end
end
